name: Build and test

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test   
      uses: b3b00/coverlet-action@1.2.5
      with:
        testProject: '**/**.Tests.csproj'
        output: 'test-results/coverage.json '
        outputFormat: 'json'
        excludes: '[program]*,[test]test.*'
        threshold: 80

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.16.1
      with:
        files: |
          test-results/**/*.json