name: Build and test

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=json%2copencover /p:CoverletOutput=test-results /p:MergeWith=test-results/coverage.json'
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.16.1
      with:
        files: |
          test-results/**/*.json